// Geekatplay TerraForge — English dictionary, identity half (b).
// GENERATED by tools/i18n_scan.py from every tr("...") in studio/:
// strings whose tag is the English text. Re-run the script after
// adding strings; do not edit by hand.
namespace studio {
static const char *const TAGS[] = {
    "Restore from trash", "Results land in %s and in the asset index.", "Samples",
    "Sculpt: brush directly on the terrain", "Seed (0 random)", "Select an object or a node.",
    "Set as the sky when done", "Set preview end here", "Set preview start here",
    "Set range end here", "Set range start here", "Shadows", "Show curve", "Show in timeline",
    "Show the console", "Show this track's curve", "Simplify", "Size", "Smooth",
    "Smooth (auto tangents)", "Snap", "Snap to frames", "Solidify", "Speed", "State",
    "Stop and go to start", "Sun altitude.", "Sun azimuth.", "Sun intensity.",
    "Target triangles", "Textured",
    "The driver does not report video memory over OpenGL (NVIDIA and AMD do).",
    "The governor is off (Settings > General).",
    "The last graph evaluation, and how many terrain patches survived culling this frame.",
    "This process's share of every core.",
    "This process's working set (peak), and the memory the system still has free.", "Timeline",
    "Toolbar and viewport icons, and the Objects panel's row height.", "Track",
    "Undo the last change  (Ctrl+Z)", "Use as sky", "Use on material",
    "Use on the material open in the studio", "VRAM %s / %s", "VRAM n/a",
    "Video memory in use / total, as the driver reports it.", "Viewport",
    "Viewport (free orbit)", "Water", "What", "What the repair did",
    "Which camera the perspective views look through.", "Width", "a note about it",
    "a weathered granite boulder...", "add a tag", "albedo", "amp", "analyse",
    "avoid (optional)", "bypassed", "choose file...", "clouds", "computing %d/%d",
    "computing %s (%d/%d)", "computing...", "consistent", "critical",
    "describe it: wet mossy granite, fine cracks...", "detecting...",
    "double-click: open\nright-click: tag, note, trash",
    "drag keys and handles; Alt breaks a handle; wheel zooms value, Ctrl+wheel time", "engine",
    "eval %.0f ms  %d nodes  %d patches", "expression, e.g. sin(t*2)*0.3 + value",
    "fall back to English", "field", "filter tracks", "final",
    "find by name, folder, tag or note...", "focal", "fog", "folder to add", "frame",
    "frame %.1f ms  ui %.1f  views %.1f  gpu %.1f", "freq", "governor off", "governor: full",
    "heightmap", "idle", "import mesh", "input", "install: %s", "live", "max", "mesh tools",
    "min", "mixed", "modifiers", "no", "no such port", "nodes that accept a %s", "note",
    "nothing accepts a %s - showing everything", "nothing connected", "nothing matches", "oct",
    "open image", "output", "parameters", "pause", "phase", "play", "points", "range",
    "reference picture (image-to-3D, optional; Hitem3D needs one)", "remove", "remove tag",
    "rendering sequence...", "rendering...", "repair", "res", "search nodes...", "seed",
    "shadows", "shape", "show all domains", "sky", "starting renderer...", "starting...",
    "stop", "sun",
    "t, frame, fps, value, pi; sin cos abs min max clamp lerp pow noise; \"Camera 1\".cam.focal_mm; world.sun_azimuth",
    "tag", "tags not in the English dictionary (run tools/i18n_scan.py)", "tags: %s", "texture",
    "time", "transform keyed at", "translated", "trash", "value",
    "waiting for the first pass...", "warning", "water",
    "wheel+Ctrl zoom, middle-drag pan, Home fit, A fit selection", "window",
    "workflow (bundled text_to_image, or a name in your ComfyUI workflows folder)", "yes",
};
const char *const *i18n_en_ui_b(int *n) {
  *n = (int)(sizeof TAGS / sizeof TAGS[0]);
  return TAGS;
}
} // namespace studio
