// Geekatplay TerraForge — English dictionary, identity half (a).
// GENERATED by tools/i18n_scan.py from every tr("...") in studio/:
// strings whose tag is the English text. Re-run the script after
// adding strings; do not edit by hand.
namespace studio {
static const char *const TAGS[] = {
    "  (in trash)", "%d links", "%d objects", "%d triangles", "%s nodes",
    "%zu -> %zu triangles, worst deviation %s (%.2f%%)", "%zu assets, %s",
    "%zu location(s), spread over %s", "%zu nodes \xC2\xB7 %.0f MB \xC2\xB7 %.0f ms",
    "(free camera)", "...more, keep typing",
    "A texture is asked for as a seamless top-down tile; a skydome as a 2:1 equirectangular panorama.",
    "AI image", "AI jobs", "AI model", "Active camera", "Add",
    "Add a camera first (Objects panel).", "Add camera",
    "Add its key in Settings > AI services", "Add key", "Add key here", "Add marker",
    "Add modifier", "After", "After last key", "Analyse", "Animated - click to key this frame",
    "Animated only", "Any resolution 64..8192, Enter to apply.", "Autokey",
    "Autokey - on: editing an animated property writes a key at the current frame", "Bake",
    "Bake 4k exports\n\nRe-evaluate at 4096 with every export node enabled.", "Bake to frames",
    "Before", "Before first key", "Browse...", "CPU %.0f%% of %d", "Cancel",
    "Choose tracks in the Timeline (the > at the right of a row, or double-click it).",
    "Clear finished", "Clear list", "Click an issue to mark it in the viewport.",
    "Click to animate: key this value here", "Clouds", "Collapse to the title bar",
    "Compact: hide the preview", "Copy",
    "Current frame. Type a frame, a timecode or seconds (1.5s).", "Curves", "Delete",
    "Detect installed engines", "Disconnect", "Disconnect all",
    "Dock this window back into the main layout", "Duplicate at frame", "Ease in", "Ease out",
    "Easy ease", "Engine", "Engines: %s", "Every frame", "Expand", "Export...",
    "FPS %.0f (%.0f possible)", "File", "File units", "Fit", "Flatten",
    "Folders the index watches", "Folders...", "Free camera", "Generate", "Generate 3D model",
    "Generate a 3D model from a prompt or a picture (Meshy, Tripo, Hitem3D).",
    "Generate an image, a tileable texture or a 360 skydome.", "Generate image", "Go to end",
    "Go to end (End)", "Go to start", "Go to start (Home)", "Height", "Hold (step)",
    "Icon size", "Import", "Import OBJ, STL, PLY or OFF and analyse it",
    "Import into the scene when done", "Import mesh...", "Interpolation", "Issues", "Job",
    "Jobs...", "Keep redrawing at the rate chosen; off, only Refresh.",
    "Key on this frame - click to remove", "Key the selected object's transform (K)", "Keys",
    "Language", "Linear", "Marker", "Match with viewport", "Material Editor", "Measure",
    "Measured on the repaired mesh, not predicted.", "Mirror in time", "Move to trash", "Name",
    "Next frame", "Next key", "No problems found. This mesh is ready to slice.", "Norm",
    "Not done: %s", "Nothing indexed yet. Folders... adds a place to look.",
    "Nothing is animated. Click a property's circle to key it.", "Nothing matches.",
    "Nothing needed changing.", "OBJ, STL, PLY, OFF",
    "Off: every keyable property of the selected object and node is listed so a key can be added here.",
    "Open", "Open file", "Output", "Paste at frame", "Play / pause (Space in the timeline)",
    "Play and render only the band on the ruler (drag its ends).",
    "Play every frame instead of keeping real time.", "Press Analyse to measure this mesh.",
    "Preview range", "Preview range from selection", "Previous frame", "Previous key",
    "Progress", "Provider", "RAM %s (peak %s)  free %s / %s", "Rebuild as a solid",
    "Rebuild as quads", "Recompute the whole graph  (F5)", "Redo  (Ctrl+Y)", "Reduce",
    "Refresh", "Remove animation", "Remove key", "Remove marker", "Render",
    "Render scale of the live view: lower is faster.", "Render settings of %s",
    "Render with %s", "Repair", "Rescan", "Rescan all",
};
const char *const *i18n_en_ui_a(int *n) {
  *n = (int)(sizeof TAGS / sizeof TAGS[0]);
  return TAGS;
}
} // namespace studio
