#!/usr/bin/env python3
"""Regenerate docs_private/NODE_AUDIT.md - the node audit ledger.

The ledger is generated from two sources so it cannot drift from reality:

  docs/node_index.json          what the registry actually contains, written
                                by tools/gen_node_index.cpp
  docs_private/node_audit_status.json
                                what a human has decided about each node -
                                its status, its display name, what reference
                                it was compared against, what was added

Regenerating never loses a decision: the status file is the record and this
only formats it. A node that appears in the registry and not in the status
file shows as `pending`, which is the honest default for something nobody has
looked at yet.

    python scripts/gen_node_audit_ledger.py
"""
import json
import os
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "docs", "node_index.json")
STATUS = os.path.join(ROOT, "docs_private", "node_audit_status.json")
OUT = os.path.join(ROOT, "docs_private", "NODE_AUDIT.md")

STEPS = [
    ("ref", "compared against the reference (Vue / Terragen / C4D / Substance)"),
    ("enhanced", "controls widened or added beyond the reference"),
    ("preview", "shows the user what it is doing"),
    ("ports", "connectors carry and accept the right data"),
    ("tested", "exercised in a real workflow"),
    ("docs", "documented"),
    ("described", "description and per-parameter tooltips"),
    ("named", "display name a person would choose"),
]

# What keeps a step true once it is true. A step nothing enforces is a claim
# about the past; a step a test enforces is a claim about the next commit too.
GUARD = {
    "ports": "`tests/cpp/test_nodes.cpp` - contract battery",
    "docs": "`tools/gen_node_docs.cpp` - regenerated from the registry",
    "described": "`tests/cpp/test_nodes.cpp` + `tools/node_audit.cpp`",
    "named": "`tests/cpp/test_nodes.cpp` + `tests/cpp/test_node_names.cpp`",
}


def load(path, default):
    if not os.path.exists(path):
        return default
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def main():
    index = load(INDEX, None)
    if index is None:
        raise SystemExit("docs/node_index.json is missing - build and run "
                         "the node_index_gen target first")
    status = load(STATUS, {"schema": 1, "nodes": {}})
    st = status.get("nodes", {})

    nodes = index["nodes"]
    planned = [n for n in nodes if n["description"].startswith("[Planned]")]
    real = [n for n in nodes if not n["description"].startswith("[Planned]")]

    done = sum(1 for n in real if st.get(n["type"], {}).get("status") == "done")

    by_cat = {}
    for n in real:
        by_cat.setdefault(n["category"], []).append(n)

    L = []
    L.append("# Node audit ledger")
    L.append("")
    L.append("Generated by `scripts/gen_node_audit_ledger.py` from "
             "`docs/node_index.json` (what the registry contains) and "
             "`docs_private/node_audit_status.json` (what has been decided). "
             "Do not edit this file - edit the status file and regenerate.")
    L.append("")
    L.append(f"**{done} of {len(real)} implemented nodes fully audited.** "
             "A node counts as done only when every step below is done, so "
             "that number moves late; the step table is where the work "
             "actually shows. "
             f"{len(planned)} `[Planned]` placeholders are listed at the end; "
             "they are the record of what the catalogue does not have yet, "
             "which is a different question from whether what it has explains "
             "itself.")
    L.append("")
    L.append("## Progress by step")
    L.append("")
    L.append("| Step | Means | Done | Enforced by |")
    L.append("| :--- | :--- | ---: | :--- |")
    for key, meaning in STEPS:
        n_done = sum(1 for n in real if key in st.get(n["type"], {})
                     .get("steps", []))
        L.append(f"| `{key}` | {meaning} | {n_done}/{len(real)} | "
                 f"{GUARD.get(key, '— (needs a person)')} |")
    L.append("")
    L.append("A step with a guard listed cannot silently regress: the check "
             "runs in CI over every registered node, and a node added "
             "tomorrow has to satisfy it before the suite goes green. A step "
             "without one is a judgement somebody made once, and is only as "
             "current as the last time they made it.")
    L.append("")
    L.append("## Progress by category")
    L.append("")
    L.append("| Category | Nodes | Steps done | Fully audited |")
    L.append("| :--- | ---: | ---: | ---: |")
    for cat in sorted(by_cat):
        ns = by_cat[cat]
        d = sum(1 for n in ns if st.get(n["type"], {}).get("status") == "done")
        steps = sum(len(set(st.get(n["type"], {}).get("steps", [])) &
                        {k for k, _ in STEPS}) for n in ns)
        L.append(f"| {cat} | {len(ns)} | {steps}/{len(ns) * len(STEPS)} | {d} |")
    L.append("")

    for cat in sorted(by_cat):
        L.append(f"## {cat}")
        L.append("")
        L.append("| Node | Display name | Steps done | Status | Reference | "
                 "Notes |")
        L.append("| :--- | :--- | :--- | :--- | :--- | :--- |")
        for n in sorted(by_cat[cat], key=lambda x: x["type"]):
            s = st.get(n["type"], {})
            have = set(s.get("steps", []))
            L.append("| `{}` | {} | {} | {} | {} | {} |".format(
                n["type"],
                s.get("display_name", "—"),
                " ".join(f"`{k}`" for k, _ in STEPS if k in have) or "—",
                s.get("status", "pending"),
                s.get("reference", "—"),
                s.get("notes", "").replace("|", "\\|") or "—"))
        L.append("")

    if planned:
        L.append("## `[Planned]` placeholders")
        L.append("")
        L.append("Registered so the gap is visible and named, with no ports "
                 "and a `plan` attribute standing in for the real ones. Each "
                 "is a node the references have and we do not.")
        L.append("")
        L.append("| Node | Category | What it will be |")
        L.append("| :--- | :--- | :--- |")
        for n in sorted(planned, key=lambda x: (x["category"], x["type"])):
            desc = n["description"].replace("[Planned]", "").strip()
            L.append(f"| `{n['type']}` | {n['category']} | {desc} |")
        L.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}: "
          f"{done}/{len(real)} audited, {len(planned)} planned")


if __name__ == "__main__":
    main()
