#!/usr/bin/env python3
"""Regenerate docs_private/NODE_AUDIT.md - the node audit ledger.

The ledger is generated from two sources so it cannot drift from reality:

  docs/node_index.json          what the registry actually contains, written
                                by tools/gen_node_index.cpp
  docs_private/node_audit_status.json
                                what a human has decided about each node -
                                its status, its display name, what reference
                                it was compared against, what was added

Regenerating never loses a decision: the status file is the record and this
only formats it. A node that appears in the registry and not in the status
file shows as `pending`, which is the honest default for something nobody has
looked at yet.

    python scripts/gen_node_audit_ledger.py
"""
import json
import os
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "docs", "node_index.json")
STATUS = os.path.join(ROOT, "docs_private", "node_audit_status.json")
OUT = os.path.join(ROOT, "docs_private", "NODE_AUDIT.md")

STEPS = [
    ("ref", "compared against the reference (Vue / Terragen / C4D / Substance)"),
    ("enhanced", "controls widened or added beyond the reference"),
    ("preview", "shows the user what it is doing"),
    ("ports", "connectors carry and accept the right data"),
    ("tested", "exercised in a real workflow"),
    ("docs", "documented"),
    ("described", "description and per-parameter tooltips"),
    ("named", "display name a person would choose"),
]


def load(path, default):
    if not os.path.exists(path):
        return default
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def main():
    index = load(INDEX, None)
    if index is None:
        raise SystemExit("docs/node_index.json is missing - build and run "
                         "the node_index_gen target first")
    status = load(STATUS, {"schema": 1, "nodes": {}})
    st = status.get("nodes", {})

    nodes = index["nodes"]
    planned = [n for n in nodes if n["description"].startswith("[Planned]")]
    real = [n for n in nodes if not n["description"].startswith("[Planned]")]

    done = sum(1 for n in real if st.get(n["type"], {}).get("status") == "done")

    by_cat = {}
    for n in real:
        by_cat.setdefault(n["category"], []).append(n)

    L = []
    L.append("# Node audit ledger")
    L.append("")
    L.append("Generated by `scripts/gen_node_audit_ledger.py` from "
             "`docs/node_index.json` (what the registry contains) and "
             "`docs_private/node_audit_status.json` (what has been decided). "
             "Do not edit this file - edit the status file and regenerate.")
    L.append("")
    L.append(f"**{done} of {len(real)} implemented nodes audited.** "
             f"{len(planned)} `[Planned]` placeholders are listed at the end; "
             "they are the record of what the catalogue does not have yet, "
             "which is a different question from whether what it has explains "
             "itself.")
    L.append("")
    L.append("## What an audited node has been checked for")
    L.append("")
    L.append("| Step | Means |")
    L.append("| :--- | :--- |")
    for key, meaning in STEPS:
        L.append(f"| `{key}` | {meaning} |")
    L.append("")
    L.append("## Progress by category")
    L.append("")
    L.append("| Category | Nodes | Audited |")
    L.append("| :--- | ---: | ---: |")
    for cat in sorted(by_cat):
        ns = by_cat[cat]
        d = sum(1 for n in ns if st.get(n["type"], {}).get("status") == "done")
        L.append(f"| {cat} | {len(ns)} | {d} |")
    L.append("")

    for cat in sorted(by_cat):
        L.append(f"## {cat}")
        L.append("")
        L.append("| Node | Display name | Status | Reference | Notes |")
        L.append("| :--- | :--- | :--- | :--- | :--- |")
        for n in sorted(by_cat[cat], key=lambda x: x["type"]):
            s = st.get(n["type"], {})
            L.append("| `{}` | {} | {} | {} | {} |".format(
                n["type"],
                s.get("display_name", "—"),
                s.get("status", "pending"),
                s.get("reference", "—"),
                s.get("notes", "").replace("|", "\\|") or "—"))
        L.append("")

    if planned:
        L.append("## `[Planned]` placeholders")
        L.append("")
        L.append("Registered so the gap is visible and named, with no ports "
                 "and a `plan` attribute standing in for the real ones. Each "
                 "is a node the references have and we do not.")
        L.append("")
        L.append("| Node | Category | What it will be |")
        L.append("| :--- | :--- | :--- |")
        for n in sorted(planned, key=lambda x: (x["category"], x["type"])):
            desc = n["description"].replace("[Planned]", "").strip()
            L.append(f"| `{n['type']}` | {n['category']} | {desc} |")
        L.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}: "
          f"{done}/{len(real)} audited, {len(planned)} planned")


if __name__ == "__main__":
    main()
