#!/usr/bin/env python3
"""Regenerates studio/i18n_en_ui.cpp and studio/i18n_en_ui2.cpp.

Every tr("literal") in studio/*.cpp whose tag is not in the tagged English
dictionary (i18n_en.cpp) is an identity tag: the English text is the tag.
This script collects them so the built-in dictionary declares each one, the
missing-tag ledger stays empty for English, and a translation file can be
checked for stale keys against a complete list.

    python tools/i18n_scan.py            # rewrite the two files
    python tools/i18n_scan.py --check    # exit 1 if they are out of date
"""
import os, re, sys, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STUDIO = os.path.join(ROOT, "studio")
CALL = re.compile(r'(?<![A-Za-z0-9_])tr\(\s*"((?:[^"\\]|\\.)*)"\s*\)')
TAGGED = re.compile(r'\{"((?:[^"\\]|\\.)*)",\s*"')


def collect():
    tagged = set()
    with open(os.path.join(STUDIO, "i18n_en.cpp"), encoding="utf-8") as f:
        tagged.update(TAGGED.findall(f.read()))
    tags = set()
    for path in sorted(glob.glob(os.path.join(STUDIO, "*.cpp")) +
                       glob.glob(os.path.join(STUDIO, "*.hpp"))):
        if os.path.basename(path).startswith("i18n_en"):
            continue
        with open(path, encoding="utf-8", errors="replace") as f:
            for m in CALL.finditer(f.read()):
                if m.group(1) not in tagged:
                    tags.add(m.group(1))
    return sorted(tags)


def render(tags, half, fn):
    lines = ["// Geekatplay TerraForge — English dictionary, identity half (%s)." % half,
             "// GENERATED by tools/i18n_scan.py from every tr(\"...\") in studio/:",
             "// strings whose tag is the English text. Re-run the script after",
             "// adding strings; do not edit by hand.",
             "namespace studio {",
             "static const char *const TAGS[] = {"]
    row = "   "
    for t in tags:
        item = ' "%s",' % t
        if len(row) + len(item) > 96:
            lines.append(row)
            row = "   "
        row += item
    if row.strip():
        lines.append(row)
    if not tags:
        lines.append('    "",')
    lines += ["};",
              "const char *const *%s(int *n) {" % fn,
              "  *n = (int)(sizeof TAGS / sizeof TAGS[0]);",
              "  return TAGS;", "}", "} // namespace studio", ""]
    return "\n".join(lines)


def main():
    tags = collect()
    half = (len(tags) + 1) // 2
    outputs = {
        os.path.join(STUDIO, "i18n_en_ui.cpp"): render(tags[:half], "a", "i18n_en_ui_a"),
        os.path.join(STUDIO, "i18n_en_ui2.cpp"): render(tags[half:], "b", "i18n_en_ui_b"),
    }
    stale = False
    for path, text in outputs.items():
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if old != text:
            stale = True
            if "--check" not in sys.argv:
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(text)
    print("%d identity tags" % len(tags))
    if "--check" in sys.argv and stale:
        print("i18n_en_ui*.cpp are out of date: run tools/i18n_scan.py")
        sys.exit(1)


if __name__ == "__main__":
    main()
