// Geekatplay TerraForge - tooltips for Kind::Segment's own keys
// (plant_schema_segment.cpp); the shared Transform/LOD/Attachment/Seasons
// blocks it also carries are in plant_schema_tips_shared.cpp.
#include "plant/plant_schema.hpp"

namespace gpx {
namespace plant {
namespace {

const Tip TABLE[] = {
    {Kind::Segment, "simple", "Builds a lightweight cylinder instead of the full segment pipeline, for distant or minor parts."},
    {Kind::Segment, "skin", "How the segment's surface is built: the standard generated skin, a skin copied from an object, or none."},
    {Kind::Segment, "length", "The length of the segment, in metres. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "min_length", "The shortest this segment is ever allowed to shrink to, in metres."},
    {Kind::Segment, "radius_mode", "How the radius is decided: inherited from the parent, set here, or inherited but clamped to the value here."},
    {Kind::Segment, "radius", "The segment's radius, in metres. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "inherit_ratio", "How much of the parent's radius carries over when radius is inherited."},
    {Kind::Segment, "min_radius", "The thinnest this segment is ever allowed to taper to, in metres."},
    {Kind::Segment, "radius_profile", "How the radius tapers along the segment's length, read off the horizontal axis as position 0..1."},
    {Kind::Segment, "tropism", "How strongly this segment bends toward its tropism direction as it grows. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "section", "The cross-section shape: circle, ellipse, triangle, square, star, a flat blade, or a custom profile."},
    {Kind::Segment, "section_custom", "The custom cross-section's radius, read off the horizontal axis as angle around the section 0..1."},
    {Kind::Segment, "section_squash", "Flattens or stretches the cross-section on one axis relative to the other. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "section_twist", "How many turns the cross-section rotates along the segment's length. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "axis_mode", "The shape of the segment's central axis: straight, curved up, curved down, an S curve, a spiral, or a custom curve."},
    {Kind::Segment, "axis_bend", "How far the axis bends from straight, in degrees, for the built-in curved axis modes. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "axis_curve", "The custom axis' sideways offset, read off the horizontal axis as position along the segment 0..1."},
    {Kind::Segment, "sampling_boost", "How many extra points the axis is sampled at, for a smoother curve on demanding shapes."},
    {Kind::Segment, "prevent_backfolds", "Stops the axis curve from folding back on itself, which would otherwise pinch the mesh."},
    {Kind::Segment, "shift_short_side", "Shifts the axis toward the side with less material, to balance an asymmetric cross-section."},
    {Kind::Segment, "smoothing", "How much the generated axis is smoothed after being built."},
    {Kind::Segment, "cap_enable", "Whether the top of the segment is capped, closing it off instead of leaving it open."},
    {Kind::Segment, "cap_mode", "What the cap covers: the cut at the end and the top surface, only the cut, or only the top."},
    {Kind::Segment, "cap_profile", "The cap's shape from its centre outward, read off the horizontal axis as distance from the centre 0..1."},
    {Kind::Segment, "cap_offset", "Shifts the cap up or down along the segment's axis. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "cap_smoothing", "Smooths the cap's normals so it does not read as faceted."},
    {Kind::Segment, "cap2_profile", "The secondary cap's shape from its centre outward, read off the horizontal axis as distance from the centre 0..1."},
    {Kind::Segment, "cap2_offset", "Shifts the secondary cap up or down along the segment's axis. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "cap2_smoothing", "Smooths the secondary cap's normals so it does not read as faceted."},
    {Kind::Segment, "bcap_enable", "Whether the bottom of the segment is capped."},
    {Kind::Segment, "bcap_profile", "The bottom cap's shape from its centre outward, read off the horizontal axis as distance from the centre 0..1."},
    {Kind::Segment, "bcap_offset", "Shifts the bottom cap up or down along the segment's axis. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "bcap_smoothing", "Smooths the bottom cap's normals so it does not read as faceted."},
    {Kind::Segment, "flare_number", "How many root-flare ridges swell out around the base of the segment."},
    {Kind::Segment, "flare_randomness", "How irregular the flares' spacing and size are. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "flare_height", "How far up the segment the flares reach, in metres. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "flare_swell", "How much the flares bulge the base radius outward. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "flare_depth", "How deep the grooves between flares cut in, in metres. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "flare_width", "How wide each flare ridge is around the base. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "flare_shape", "The flare's swell from base to tip, read off the horizontal axis as height along the flare 0..1."},
    {Kind::Segment, "blade_number", "How many flat blades grow along this segment (for grasses and blade-like stems)."},
    {Kind::Segment, "blade_start", "Where the blades begin along the segment. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_end", "Where the blades end along the segment. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_spread", "How wide an angle the blades are spread across around the segment, in degrees. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_spread_offset", "Rotates the whole spread of blades around the segment, in degrees. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_width", "The width of each blade, in metres. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_style", "How the blades are built: a single plane, symmetrical pairs, a full-width wrap, or a simple flat shape."},
    {Kind::Segment, "blade_autosize", "Scales each blade's width automatically to the segment's own radius instead of using a fixed width."},
    {Kind::Segment, "blade_from_axis", "Grows the blades from the segment's central axis rather than from its surface."},
    {Kind::Segment, "blade_section", "The blade's cross-section shape, read off the horizontal axis as position across its width 0..1."},
    {Kind::Segment, "blade_section_height", "How much the blade's cross-section rises out of flat. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_profile", "The blade's width along its length, read off the horizontal axis as position from base to tip 0..1."},
    {Kind::Segment, "blade_pinching", "How much the blade narrows and folds inward toward its tip. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_follow_axis", "Lets the blades bend along with the segment's own axis curve instead of staying straight."},
    {Kind::Segment, "mesh_boost", "Raises or lowers this segment's mesh resolution on top of the species-wide setting."},
    {Kind::Segment, "normal_mode", "How surface normals are computed: parametric from the profile, or geometric from the built mesh."},
    {Kind::Segment, "double_sided", "Shades both faces of the segment's surface."},
    {Kind::Segment, "axial_mode", "How the number of subdivisions along the segment's length is decided: a fixed count, one per unit length, or driven by a curve threshold."},
    {Kind::Segment, "axial_number", "The number of subdivisions along the segment's length."},
    {Kind::Segment, "axial_density", "Where subdivisions along the length concentrate, read off the horizontal axis as position 0..1."},
    {Kind::Segment, "axial_adaptive", "Lets the axial subdivision count adjust itself to the segment's curvature and length instead of staying fixed."},
    {Kind::Segment, "axial_min", "The fewest subdivisions the segment's length is ever allowed to have."},
    {Kind::Segment, "radial_mode", "How the number of subdivisions around the segment's cross-section is decided: a fixed count, one per unit radius, or driven by a curve threshold."},
    {Kind::Segment, "radial_number", "The number of subdivisions around the segment's cross-section."},
    {Kind::Segment, "radial_symmetry", "Repeats the cross-section's subdivisions in this many identical wedges, for a faceted look."},
    {Kind::Segment, "radial_min", "The fewest subdivisions the segment's cross-section is ever allowed to have."},
    {Kind::Segment, "blend_min_subdiv", "The fewest subdivisions kept across a blended join to a child."},
    {Kind::Segment, "cap_subdiv", "The number of subdivisions across the cap's radius."},
    {Kind::Segment, "cap_disp_transition", "How the segment's body displacement fades out as it approaches the cap, read off the horizontal axis as distance from the cap 0..1."},
    {Kind::Segment, "blade_subdiv", "The number of subdivisions across a blade's cross-section."},
    {Kind::Segment, "perturb_strength", "How strongly the segment's axis is perturbed with noise, away from its clean curve. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "perturb_planar", "Biases the axis perturbation to stay within one plane instead of wandering in every direction."},
    {Kind::Segment, "perturb_frequency", "How finely the axis perturbation noise oscillates along the segment. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "perturb_keep_tip", "Keeps the segment's very tip fixed in place while the rest of the axis is perturbed."},
    {Kind::Segment, "perturb_smooth_start", "Eases the perturbation in gradually from the segment's base instead of applying it at full strength immediately."},
    {Kind::Segment, "perturb_apply", "Whether the axis perturbation is applied before or after the global biases."},
    {Kind::Segment, "wind_flexibility", "How easily the segment bends under wind, independent of its thickness. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "wind_blade_influence", "How much of the segment's blades' own area adds to how much wind catches the segment. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "breeze_strength", "How far this segment sways in the ambient breeze. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "breeze_override", "Ignores the species' inherited ambient-motion settings and uses this segment's own."},
    {Kind::Segment, "blade_breeze_amplitude", "How far the segment's blades sway in the ambient breeze, separate from the segment body. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_breeze_frequency", "How fast the segment's blades oscillate in the ambient breeze. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "gust_gravity", "How strongly gravity pulls this segment back after a gust passes. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "gust_wind", "How strongly gusts push this segment, on top of the steady wind. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "bone_boost", "Raises or lowers how many skinning bones this segment's wind animation uses."},
    {Kind::Segment, "blade_flexibility", "How easily the segment's blades bend under wind and gusts. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_gravity", "How strongly gravity pulls the blades back after a gust. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_wind", "How strongly gusts push the blades, on top of the steady wind. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "global_bias_strength", "How much the species' global biases affect this segment, on top of each bias' own strength. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "bias_type", "The kind of local pull this segment adds on its own: none, direction, conic, attractor, axis repeller, swirl, curl, or twist."},
    {Kind::Segment, "bias_strength", "How strongly this segment's local bias pulls its growth. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "bias_dir_x", "The X component of this segment's local bias direction."},
    {Kind::Segment, "bias_dir_y", "The Y component of this segment's local bias direction."},
    {Kind::Segment, "bias_dir_z", "The Z component of this segment's local bias direction."},
    {Kind::Segment, "bias_local", "Measures the local bias direction in the segment's own frame instead of the world."},
    {Kind::Segment, "bias_length_agnostic", "Keeps the local bias' pull independent of the segment's own length."},
    {Kind::Segment, "bias_apply", "Which parts feel this segment's local bias: only free-floating ones, the entire segment, or only parts growing on an object."},
    {Kind::Segment, "bias_repeller", "Reverses a conic local bias into a repeller that pushes away instead of pulling in."},
    {Kind::Segment, "bias_cone_angle", "For a conic local bias, the half-angle of the cone growth is pulled toward, in degrees."},
    {Kind::Segment, "bias_base_length", "For a conic local bias, the reference length, in metres, its falloff is measured against."},
    {Kind::Segment, "bias_origin_x", "The X position of the local bias' origin point, in metres."},
    {Kind::Segment, "bias_origin_y", "The Y position of the local bias' origin point, in metres."},
    {Kind::Segment, "bias_origin_z", "The Z position of the local bias' origin point, in metres."},
    {Kind::Segment, "twist_planar", "Keeps a twist local bias' rotation confined to one plane."},
    {Kind::Segment, "twist_symmetry", "How many repeating lobes a twist local bias' rotation is folded into."},
    {Kind::Segment, "twist_target", "The angle, in degrees, a twist local bias tries to rotate the segment toward."},
    {Kind::Segment, "interact_with", "What this segment reacts to physically: nothing, the ground, an object, or both."},
    {Kind::Segment, "prune_after", "Cuts the segment short once it has grown past this length, in metres, as if pruned."},
    {Kind::Segment, "interact_perturb_ratio", "How much the collision reaction with the ground or an object perturbs the segment's axis."},
    {Kind::Segment, "mat_distribution", "How the body material is assigned across segments: one material per segment, per cross-section, or cycling in sequence."},
    {Kind::Segment, "disable_baking", "Skips baking this segment's texture detail into vertex data, keeping it live instead."},
    {Kind::Segment, "disable_blade_baking", "Skips baking the blades' texture detail into vertex data, keeping it live instead."},
    {Kind::Segment, "uv_mode", "How the body's texture coordinates are laid out: standard, parametric along U only, or parametric on both axes."},
    {Kind::Segment, "u_tile", "How many times the body material repeats around the segment."},
    {Kind::Segment, "v_tile", "How many times the body material repeats along the segment's length."},
    {Kind::Segment, "u_offset", "Shifts the body material's texture coordinates around the segment."},
    {Kind::Segment, "v_offset", "Shifts the body material's texture coordinates along the segment's length."},
    {Kind::Segment, "uv_twist", "Twists the body material's texture coordinates along the segment's length."},
    {Kind::Segment, "keep_aspect", "Keeps the body material's texture undistorted in aspect ratio as the segment tapers."},
    {Kind::Segment, "map_v_from_end", "Measures the body material's V coordinate from the tip instead of the base."},
    {Kind::Segment, "extend_top_cap", "Extends the body material's texture coordinates onto the top cap instead of giving the cap its own mapping."},
    {Kind::Segment, "extend_bottom_cap", "Extends the body material's texture coordinates onto the bottom cap instead of giving it its own mapping."},
    {Kind::Segment, "detail_uv_mode", "How texture coordinates for a secondary detail layer are laid out: standard, parametric along U only, or parametric on both axes."},
    {Kind::Segment, "detail_u_tile", "How many times the detail layer repeats around the segment."},
    {Kind::Segment, "detail_v_tile", "How many times the detail layer repeats along the segment's length."},
    {Kind::Segment, "rdisp_source", "What drives the radial (bark-like) surface displacement: none, noise, bark ridges, knots, or an input field."},
    {Kind::Segment, "rdisp_relative", "Scales the radial displacement by the segment's own radius, so thin and thick segments displace proportionally."},
    {Kind::Segment, "rdisp_amount", "How far the surface is pushed in and out radially. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "rdisp_offset", "Shifts the radial displacement pattern up or down before it is applied."},
    {Kind::Segment, "rdisp_scale", "How large the radial displacement pattern reads on the surface."},
    {Kind::Segment, "disp3_amount", "How far the surface is pushed by the free-form 3D displacement. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "disp3_offset", "Shifts the 3D displacement pattern before it is applied."},
    {Kind::Segment, "disp3_scale", "How large the 3D displacement pattern reads on the surface."},
    {Kind::Segment, "cap_mat_angle", "Rotates the cap's material texture, in degrees."},
    {Kind::Segment, "cap_mat_scale", "Scales the cap's material texture."},
    {Kind::Segment, "cap_border", "How much of the cap near its edge is treated separately for material blending."},
    {Kind::Segment, "cap_disp_amount", "How far the cap's surface is displaced. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "cap_disp_offset", "Shifts the cap's displacement pattern before it is applied."},
    {Kind::Segment, "blade_dist_mode", "How materials are assigned across blades: one per segment, one per blade, or cycling in sequence."},
    {Kind::Segment, "blade_uv_mode", "How texture coordinates on the blades are laid out: standard, parametric along U only, or parametric on both axes."},
    {Kind::Segment, "blade_uv_extension", "Extends the blade's texture coordinates so the material continues smoothly from the segment body."},
    {Kind::Segment, "blade_map_v_from_end", "Measures the blade material's V coordinate from the tip instead of the base."},
    {Kind::Segment, "blade_u_tile", "How many times the blade material repeats across the blade's width."},
    {Kind::Segment, "blade_v_tile", "How many times the blade material repeats along the blade's length."},
    {Kind::Segment, "blade_u_offset", "Shifts the blade material's texture coordinates across its width."},
    {Kind::Segment, "blade_v_offset", "Shifts the blade material's texture coordinates along its length."},
    {Kind::Segment, "blade_disp_amount", "How far the blade's surface is displaced along its normal. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_disp_radial", "How far the blade's surface is displaced radially, curling it. The value may be given a spread and shaped along the part / by the hierarchy curve."},
    {Kind::Segment, "blade_disp_offset", "Shifts the blade's displacement pattern before it is applied."},
    {Kind::Segment, "sap_inherit", "How much of the parent's sap (vigour) this segment inherits, which feeds its own growth."},
};

struct Reg {
  Reg() { tips_register(TABLE, sizeof TABLE / sizeof TABLE[0]); }
} reg_;

} // namespace
} // namespace plant
} // namespace gpx
